// A simple cache interface.

// Type for cache errors.
enum error {
    runtime-error,
    not-found-error,
}

// Payload for cache values.
type payload = list<u8>

// Set the payload for the given key.
set: func (key: string, value: payload, ttl: option<u32>) -> expected<unit, error>

// Get the payload stored in the cache for the given key.
get: func(key: string) -> expected<payload, error>

// Delete the cache entry for the given key.
delete: func(key: string) -> expected<unit, error>
