[package]
    name    = "rust-consumer"
    version = "0.1.0"
    edition = "2021"


[dependencies]
    anyhow           = "1.0"
    wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "v0.2.0" }

[workspace]
